[paths]
wishlist = /root/sc/config/wanted.txt
save_directory = /root/sc/data/captures
up_directory = /root/sc/data/up
log_directory = /root/sc/data/logs

[settings]
checkInterval = 20
segmentDuration = 30
proxy =

[web]
host = 127.0.0.1
port = 18080
base_path = /sc
